name: Keep Render Alive
on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
jobs:
  curl-job:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Render Backend Active
        run: curl -X GET https://cogniqedge-backend.onrender.com
